services:
  # Serviço do Banco de Dados MongoDB
  mongo:
    image: mongo:6.0
    container_name: diario-mongo
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017" # Mapeia a porta do host (variável) para a porta fixa do container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db # Persiste os dados mesmo se apagar o container

  # Serviço da Aplicação (Opcional, para rodar tudo junto)
  app:
    build: .
    container_name: diario-app
    ports:
      - "3000:3000"
    environment:
      # Usa a variável definida externamente (ex: Atlas) OU monta a local padrão se não houver
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB:-diario_de_classe}?authSource=admin}
    depends_on:
      - mongo

volumes:
  mongo_data:
